language: python
python:
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.9.2

# command to install dependencies
install:
#  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
#  - python setup.py -q install
# command to run tests
script: python manage.py test --settings=strongMan.settings.local
