sudo: required

services:
  - docker

language: python
python:
  - "3.4"
  - "3.5"

before_install:
  - docker build -t strongman docker/
  - docker run strongman /bin/sh -c "cd /StrongMan/; python manage.py test --settings=strongMan.settings.local"


script: python manage.py test --settings=strongMan.settings.local




